/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertSnack: typeof import('./components/AlertSnack.vue')['default']
    DialogAlert: typeof import('./components/dialogAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserList: typeof import('./components/UserList.vue')['default']
    UserModal: typeof import('./components/UserModal.vue')['default']
  }
}
